CREATE DATABASE TechWorld
GO
USE TechWorld
GO

CREATE TABLE TaiKhoan(
	TaiKhoan NVARCHAR(50) NOT NULL,
	MatKhau NVARCHAR(50) NOT NULL,
	PRIMARY KEY (TaiKhoan)
);

CREATE TABLE NhaCungCap(
	MaNCC INT IDENTITY(1,1),
	TenNCC NVARCHAR(100) NOT NULL,
	SoDienThoaiNCC NVARCHAR(20) NOT NULL,
	DiaChiNCC NVARCHAR(200) NOT NULL,
	HinhAnh NVARCHAR(1000),
	PRIMARY KEY (MaNCC)
);

CREATE TABLE LoaiHang(
	MaLoai INT IDENTITY(1,1) PRIMARY KEY,
	TenLoai NVARCHAR(100) NOT NULL,
	HinhAnh NVARCHAR(1000),
);

CREATE TABLE SanPham(
	MaSP INT IDENTITY(1,1) PRIMARY KEY,
	TenSP NVARCHAR(100) NOT NULL,
	NgayNhap DATE NOT NULL,
	GiaTien FLOAT NOT NULL,
	GiaTienDaKhuyenMai FLOAT,
	SoLuong INT NOT NULL,
	MoTa NVARCHAR(MAX) NOT NULL,
	MoTaSanPham NVARCHAR(MAX) NOT NULL,
	HinhAnh NVARCHAR(1000),
	GiamGia NVARCHAR(10),
	TinhTrangSP NVARCHAR(50),
	MaLoai INT,
	MaNCC INT,
    FOREIGN KEY (MaLoai) REFERENCES LoaiHang(MaLoai),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE KhachHang(
	MaKH INT IDENTITY(1,1) PRIMARY KEY,
	HoTen NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR (200),
	SoDienThoai NVARCHAR(20),
	MatKhau NVARCHAR(20) NOT NULL,
	HinhAnh NVARCHAR(1000),
);


CREATE TABLE DonHang(
	MaDH INT IDENTITY(1,1) PRIMARY KEY,
	NgayDat DATETIME DEFAULT GETDATE(),
	TongTien FLOAT NOT NULL,
	PTThanhToan NVARCHAR(100),
	TTDonHang NVARCHAR(50),
	TTThanhToan NVARCHAR(50),
	MAKH INT,
	FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE ChiTietDonHang(
	MaDH INT,
	MaSP INT,
	NgayDat DATETIME DEFAULT GETDATE(),
	TongTien FLOAT NOT NULL,
	PRIMARY KEY (MaDH, MaSP),
	FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE YeuThich (
    MaKH INT,
    MaSP INT,
    NgayThemVao DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (MaKH, MaSP),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE TinTuc (
    MaTin INT PRIMARY KEY IDENTITY(1,1),
    TieuDe NVARCHAR(255) NOT NULL,
    NoiDung NVARCHAR(MAX),
    NgayDang DATE DEFAULT CAST(GETDATE() AS DATE),
    TacGia NVARCHAR(100),
    HinhAnh NVARCHAR(255),
    TrangThai NVARCHAR(20) DEFAULT N'Công khai'
);


